name: Pre-Prod Sanity Check

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Pre-prod - ViBE
    if: github.repository == 'byjackli/vibe'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: installing packages
        run: npm install
      - name: running tests
        run: npm run test
      - name: building code base
        run: npm run build
      - name: deploying preview
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIBE_BYJACKLI }}'
          channelId: preview
          projectId: vibe-byjackli